sudo: required
services:
  - docker
before_install:
  - docker build -t mosh2020/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mosh2020/react-test npm run test

after_success:
  - docker build -t mosh2020/multi-client ./client
  - docker build -t mosh2020/multi-nginx ./nginx
  - docker build -t mosh2020/multi-server ./server
  - docker build -t mosh2020/multi-worker ./worker
# login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images to docker hub
  - docker push mosh2020/multi-client
  - docker push mosh2020/multi-nginx
  - docker push mosh2020/multi-server
  - docker push mosh2020/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-149501274876"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key: "$SECRET_ACCESS_KEY"

