sudo: required
services:
  - docker
before_install:
  - docker build -t mosh2018/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mosh2018/react-test npm run test

after_success:
  - docker build -t mosh2018/multi-client ./client
  - docker build -t mosh2018/multi-nginx ./nginx
  - docker build -t mosh2018/multi-server ./server
  - docker build -t mosh2018/multi-worker ./worker
